baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "saulgh.xyz"
theme: hugo-profile

Paginate: 3
googleAnalytics: UA-138961837-1

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
    # - identifier: blog
      # name: Blog
      # title: Blog posts
      # url: /blogs
      # weight: 1

    # - identifier: gallery
      # name: Gallery
      # title: Blog posts
      # url: /gallery
      # weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "saulgh.xyz"
  description: "CEO & Co-Founder of StageInHome, an AI-powered proptech startup. Entrepreneur onboarded on other projects pivoting on newspace and web3 technologies. Speaker on congresses and Lecturer on Innovation and Entrepreneurship topics at University."
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
   color:
     textColor: <000000>
     secondaryTextColor: <4D4D4D>
     backgroundColor: <linear-gradient(to right, 5D26C1, a17fe0, 59C173)>
     secondaryBackgroundColor: <FFFFFF>
     primaryColor: <5D26C1>
     secondaryColor: <59C173>

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  menus:
    disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    # intro: "Hi, my name is"
    title: "Saul Garcia Huertes."
    subtitle: "Startup CEO & Co-founder. Tech Strategist. Lecturer."
    content: "🚀 CEO & Co-founder of stageinhome.com, disrupting the proptech industry with an AI approach. 💡 Co-founder of tracksco2.com (newspace applications for a decarbonizated economy) and tokeneat.xyz (web3, blockchain and a new angle for NFT applications). 📣 Speaker and Management Consultant on Digital Transformation topics. 🎓 Phd Student, and University Lecturer on Innovation and Entrepreneurship."
    image: /images/hero.svg
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/saulgh/
        - icon: fab fa-twitter
          url: https://twitter.com/sgar2209
      #customIcons:
      #  - icon: /fav.png
      #    url: "https://example.com"

  # About
  about:
    enable: false
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA.

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "CEO and Co-Founder"
        company: "StageInHome"
        companyUrl: "https://www.stageinhome.com"
        date: "June 2020 - Present"
        featuredLink:
          enable: true
          name: "Check our AI-powered service for virtual home staging"
          url: "https://stageinhome.com/home-staging-virtual"
        info:
          enable: false
          content: "Full dedication"
        content: |
          - Designed and refined business model, including product release schedule and acquisition of initial funding from angel investors to sustain operations through launch, to eventually raising 0,5M€ as pre-seed investment round.
          - Managed marketing, commercial and growth strategies, while maintaining proper financial control and reporting. Expected +100K € in sales revenue in 2022, that is less than 6 months after releasing our MVP.
          - Developed sales strategy with focus on new business development pipeline for 2023 and 2024. Already started prospective meetings with focus on client acquisition for potential big accounts in real estate and retail industries.
          - Built and led a motivated engineering team of +10 talented individuals to focus on product development with proprietary technology in AI/ML and CV, overseeing day to day activities to ensure alignment with our business strategy.

      - job: "Digital Transformation Advisor"
        company: "Napptilus Tech Labs"
        companyUrl: "https://napptilus.com"
        date: "January 2021 - Present"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: "Partial dedication"
        content: |
          - Led innovation with an agile mindset and constantly seeking for new technology approaches, to eventually design and iterate each business plan, while supporting all stages of digital transformation, from ideation to production
          - Provided strategic counsel to C-suite executives on implementation of new technologies, with focus on AI/ML and Computer Vision applications seeking for improved business processes and new market opportunities

      - job: "Lecturer"
        company: "Universitat Politècnica de Catalunya"
        companyUrl: "https://upc.edu"
        date: "September 2020 - Present"
        info:
          enable: true
          content: "Partial dedication"
        featuredLink:
          enable: true
          name: "UPC Profile page"
          url: "https://directori.upc.edu/directori/dadesPersona.jsp?id=1058150"
        content: |
          - Taught classes on innovation, entrepreneurship and lean startup topics, for both graduate and master students, within the EIT (European Institute of Innovation & Technology).

      - job: "Consulting Manager"
        company: "Accenture"
        companyUrl: "https://www.accenture.com"
        date: "September 2015 - January 2021"
        info:
          enable: false
          content: "Partial dedication"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Drove the program management for different clients, ranging from industry leader cloud implementations to custom-made digital ecosystems design, being the ultimate responsible for the PnL and their delivery, successfully rolling out in +20 countries with +100K potential users
          - Subject matter expert on digital transformation topics, defined strategy recommendations and led design thinking workshops to a number of clients from dissimilar industries, with a feasible but innovative approach
          - Solid business developer, became a trustable partner for my clients that led to consistent sales figures, up to +2MM€ over the last fiscal year, while contributing as SME to new sales origination on digital transformation topics
          - As part of the executive committee I was involved in Accenture's Operations Management, mostly leading new recruiting initiatives to attract talent from top universities despite budgeting constraints

      - job: "Commercial Manager"
        company: "LATAM Airlines"
        companyUrl: "https://www.latamairlines.com/"
        date: "April 2014 - August 2015"
        info:
            enable: false
            content: "Partial dedication"
        content: |
          - Led a team of 4 commercial analysts, focused on gathering all the B2B and B2C traveller data, to later implement a data-driven approach to identify trends and business insights by mining both internal and external data sources
          - I was responsible for campaign definition and execution in coordination with Marketing and Commercial areas, using new sources of data to identify potential niche travellers to build ad-hoc campaigns adapted to them

      - job: "Short-term Consultant"
        company: "The World Bank Group"
        companyUrl: "https://www.worldbank.org/en/home"
        date: "November 2013 - April 2014"
        info:
            enable: true
            content: "Remote"
        content: |
          - Led the development of a strategic project within Computational Tools area, acting as a liaison between developers and end users, for the targeted research areas in Latin America and Africa.

      - job: "Senior Consultant"
        company: "Minsait - Indra Business Consulting"
        companyUrl: "https://www.minsait.com/en"
        date: "July 2013 - April 2014"
        info:
          enable: false
          content: "Partial dedication"
        content: |
          - Drove strategic plans for both public and private organisations in EU and LATAM, including due diligence, M&A analyses, economic models and roadmap recommendations to ease decision making process for my clients.

      - job: "Management Consultant"
        company: "Accenture"
        companyUrl: "https://www.accenture.com"
        date: "October 2009 - August 2012"
        info:
            enable: false
            content: "Partial dedication"
        content: |
          - Improved performance of clients' targeted activities in their different affiliates across Europe. I put forward tailored solutions, coordinated teams and ran the value realisation office for C-Level reporting.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: true
    items:
      - title: "PhD candidate in Economics & Innovation"
        school:
          name: "Universidad Autonoma de Madrid"
          url: "https://www.uam.es"
        date: "2015 - 2023"
        #GPA: "3.8 out of 5.0"
        #content: |-
          #Extracurricular Activities
            #- Lorem ipsum dolor sit amet consectetur adipisicing elit.
            #- Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "MSc in Innovation Management"
        school:
          name: "Maastrich University"
          url: "https://www.maastrichtuniversity.nl/"
        date: "2012 - 2013"
        #GPA: "3.9 out of 5.0"
        #content: |-
        #  I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #  - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #  - Face mask detection using a single convolutional neural network.

        #  Extracurricular Activities
        #    - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        #    - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # featuredLink:
        #  enable: true
        #  name: "My academic record"
        #  url: "https://example.com"
      - title: "BSc in Business Science"
        school:
          name: "Universitat de Barcelona"
          url: "https://www.ub.edu/web/portal/en/"
        date: "2006 - 2010"
        #GPA: "3.9 out of 5.0"
        #content: |-
        #  I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #  - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #  - Face mask detection using a single convolutional neural network.

        #  Extracurricular Activities
        #    - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        #    - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # featuredLink:
        #  enable: true
        #  name: "My academic record"
        #  url: "https://example.com"
      - title: "MSc and BSc in Telecommunications Engineering"
        school:
          name: "BCN Telecom, Universitat Politècnica de Catalunya"
          url: "https://www.upc.edu/en"
        date: "2003 - 2009"
        #GPA: "3.9 out of 5.0"
        #content: |-
        #  I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #  - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #  - Face mask detection using a single convolutional neural network.

        #  Extracurricular Activities
        #    - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        #    - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # featuredLink:
        #  enable: true
        #  name: "My academic record"
        #  url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Custom Name"
    items:
      - title: AUCOOP Co-Founder
        content: NGO to leverage tech in education for UPC students. I had to opportunity to volunteer in Peru, Chile and Colombia.
        url: "https://aucoop.upc.edu/ca"
      - title: Telecogresca Alumni
        content: Had the honour to be part of the team that makes possible every year the celebration of the biggest music concert organized by university students in Europe.
        url: "https://telecogresca.com"
      - title: Scrum Master Certified (SMC)
        content: Certified by Scrum-Alliance in 2019.
        url: "https://bcert.me/srdzdytwr"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Catalan Pitch Competition
        content: I really had fun pitching on this event!
        image: /images/projects/CatalanPitch.jpeg
        badges:
           - "Pitch"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/posts/saulgh_startups-techspiritbarcelona-activity-6868943967325585409-wfbq?utm_source=share&utm_medium=member_desktop

      - title: Press presence
        content: One of our first press interviews thanks to La Vanguardia
        image: /images/projects/LaVanguardia.png
        badges:
           - "Press"
        links:
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/posts/saulgh_proptech-artificialintelligence-homestaging-activity-6789887062054064128-Wi-P?utm_source=share&utm_medium=member_desktop

      - title: ESADE & Idealista Real Estate Challenge
        content: Participated on the open challenge to proptech startups, and we luckily won!
        image: /images/projects/RealEstateChallenge.png
        #featured:
        #  name: Demo V2
        #  link: https://hugo-profile-2.netlify.app
        badges:
          - "Pitch"
          - "Challenge"
        #   - "Javascript"
        links:
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/posts/saulgh_stageinhome-ganador-del-esade-alumni-idealista-activity-6781319696772808704-GBwo?utm_source=share&utm_medium=member_desktop


  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: me@saulgh.xyz
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      #github: https://github.com
      linkedin: https://www.linkedin.com/in/saulgh/
      twitter: https://twitter.com/sgar2209
      #instagram: https://instagram.com
      #facebook: https://facebook.com
